import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.nav}>
            <a>contact</a>
            <a>blog</a>
            <a>resume</a>
          </div>
          <h1 className={styles.title}>
            <a>Jacob Haflett</a>
          </h1>
        </div>
        <div className={styles.projects}>
          <h3 className={styles.projectsTitle}>
            projects
          </h3>
            <ul>
              <li> Project 1</li>
              <li> Project 2</li>
              <li> Project 3</li>
              <li> Project 4</li>
            </ul>
        </div>
      </main>

    </div>
  )
}
